_BASE_: "COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"

MODEL:
  WEIGHTS: "detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/model_final_f10217.pkl"
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 128
    NUM_CLASSES: 2
    SCORE_THRESH_TEST: 0.5

INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333

DATASETS:
  TRAIN: ("rebar_train",)
  TEST: ("rebar_val",)

DATALOADER:
  NUM_WORKERS: 2

SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.00025
  MAX_ITER: 5000
  STEPS: (3000, 4000)
  CHECKPOINT_PERIOD: 1000

TEST:
  EVAL_PERIOD: 1000

OUTPUT_DIR: "./output_rebar_mask_rcnn"
